### PR TITLE
rolling dashboards by URL parameter

### LINKED ISSUE #12: looping through dashboard set
As I now have some more widgets on my dashboard as can be displayed on one page (it's used on a separate computer for monitoring), I modified django-dashing to automatically roll through the different dashboards in the set depending on an URL parameter. 

If you'd like to see this feature in the official django-dashing repo, I'd create that feature and a pull request (might take some days ;) ).

Please let me know if this is of interest. Thanks.

### PR DESCRIPTION
**Pull request by torstenfeld**
this should fix #12 and #11 as described in the issues and should fix the issues from the last pull request.
I added additions to the documention as well.

### CODE REVIEW

**Comment by individuo7** [comment]
Hi, excuse the lateness of the response, trying yet not works for me :s checked the reason is because in ´setInterval(function() { self.switchDashboards(); }, interval);´ instruction (line 104 of dashing.js) `self` is actually `window`.  It's because ´setupRolling´ is calling from a `setTimeout` instruction (`setTimeout(self.setupRolling, 1000);`)

Why you are calling setTimeout? without calling this should work too right?

**Comment by torstenfeld** [comment]
I set the setTimeout to be sure, that all dashboards have been added through dashing-config.js. 
Without it, I assume, that setupRolling function is executed after DashboardSet() has been called, where the dashboards have not been added yet. 

The problem is, that I was just able to reproduce the issue once but now, after installing django-dashing from my own repo, it's working fine though I didn't change anything. :(

**Comment by torstenfeld** [comment]
@individuo7 could you please test with the feature/bugfixing branch of my repo. I reverted the 84c5c0c commit, so that switchDashboards, setupRolling, ... are normal functions instead of methods. With that change, I do not encounter the error anymore.

**Comment by individuo7** [comment]
Hi @torstenfeld sorry for the late answer, (again :sweat: ) but I was offline for a week, as soon as possible I check the brach, ty :)

**Comment by individuo7** [comment]
Hi @torstenfeld I tested the branch **/feature/bugfixing** and works well, please make a pull request with this version to make the merge, thanks again

**Pull request closed without merging**
